### ISSUE TITLE
Download video/audio in the best quality by default?

### ISSUE THREAD

**Issue by wavebaka** [IIEleven11/Downloader_GUIv3#1]
Is there a method to download the video/audio in the best quality available instead of webm?

**Comment by IIEleven11** [comment]
yt-dlp uses a newer codec. I will add an option to the gui that allows selection of format where possible.

**Comment by IIEleven11** [comment]
> Is there a method to download the video/audio in the best quality available instead of webm?

I updated it to download then to convert to mp4. So it should work as suggested. This is a temporary fix until I figure out how to make the media format a user selected option.

**Comment by wavebaka** [comment]
> > Is there a method to download the video/audio in the best quality available instead of webm?
> 
> I updated it to download then to convert to mp4. So it should work as suggested. This is a temporary fix until I figure out how to make the media format a user selected option.

perfectt, working fine! thank you so much!
