### ISSUE TITLE
Program can't find .txt file

### ISSUE THREAD

**Issue by Kazserah** [IIEleven11/Downloader_GUIv3#3]
It opens a explorer window when clicking load urls, but it will not find the .txt file in the folder, it shows there's nothing there when there is. yes it's the right extension

**Comment by IIEleven11** [comment]
> It opens a explorer window when clicking load urls, but it will not find the .txt file in the folder, it shows there's nothing there when there is. yes it's the right extension

Put the txt file in the same folder as the program
